apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: production
spec:
  selector:
    app: spark-worker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: spark-ui
    - protocol: TCP
      port: 9999
      targetPort: 9999
      name: spark-worker
