apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: production
spec:
  selector:
    app: user
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: user
